### ISSUE TITLE
please update AB Reloaded android port to 3.4

### ISSUE THREAD

**Issue by IMXSwarup** [GZHYBFHHJ/gzhybfhhj.github.io#1]
i guess GZHYBFHHJ is you😀
I tried this android port of angry birds reloaded 2.2 and really awesome work
I was wonder that if angry birds reloaded 3.4 could be ported... I will be very gratefull to you if you port 3.4 version to android
in one modding channel i just saw dumps or assests of version 3.4
![Screenshot 2024-05-31 132846](https://github.com/GZHYBFHHJ/gzhybfhhj.github.io/assets/84410006/4bdc6d0d-9a37-415c-9328-47781684bd8a)

**Comment by GZHYBFHHJ** [comment]
> I tried this android port of angry birds reloaded 2.2 and really awesome work

Sadly, the APK you got is leaked one. It was supposed to be private, but idk why, the apk got leaked by someone.

> I was wonder that if angry birds reloaded 3.4 could be ported... I will be very gratefull to you if you port 3.4 version to android

nope
